parameters:
#    aldor_cytaty_s.example.class: Aldor\CytatySBundle\Example

services:
#    aldor_cytaty_s.example:
#        class: %aldor_cytaty_s.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
