parameters:
#    aldor_api.example.class: Aldor\ApiBundle\Example

services:
#    aldor_api.example:
#        class: %aldor_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
