aldor_api:
    resource: "@AldorApiBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

aldor_cytaty_s_api:
    resource: "@AldorApiBundle/Resources/config/routing.yml"
    prefix:   /api

aldor_cytaty_s:
    resource: "@AldorCytatySBundle/Resources/config/routing.yml"
    prefix:   /





