<?php

namespace Aldor\CytatySBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdsRepository extends EntityRepository
{
    public function getOneAds($weight = 1)
    {
        $qb = $this->createQueryBuilder('a')->select('max(a.id)')->where('a.onstatus =1 and a.weight ='.$weight)
     ->setMaxResults(1);

        $query = $qb->getQuery();
        $maxid = $query->getResult();

        $maxid = $maxid[0];

        $maxid = $maxid[1];
        $qb = $this->createQueryBuilder('a')->where(' a.id = :randid and a.onstatus = 1')
            ->setParameter('randid',rand(1,$maxid))
     ->setMaxResults(1)
        ;

        $query = $qb->getQuery();

    return $query->getResult();


    }

}
