#src/Aldor/StrimsCytatyBundle/Resources/config/doctrine/Quote.orm.yml
Aldor\CytatySBundle\Entity\Ads:
    type: entity
    repositoryClass: Aldor\CytatySBundle\Repository\AdsRepository
    table: ads
    id:
        id:
            type: integer
            generator: { strategy:AUTO }
    fields:
        date:
            type: datetime
        name:
            type: string
            length: 200
        type:
            type: string
            length: 255
        value:
            type: text
        onstatus:
            type: boolean
            nullable: true
            defualt: 0
        weight:
            type: integer
            defualt: 1
    lifecycleCallbacks:
            prePersist: [ setDateAtValue ]

